### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by bbernberg** [rollout/rox-ios#4]
Do you plan on adding support for SPM? Thanks in advance.

**Comment by adjunct** [comment]
@bbernberg currently we have no such plan, but I have opened a request for enhancement and would review when considering roadmap ahead.   you can follow progress here - https://feedback.cloudbees.com/app/#/case/60051

**Comment by arnauddorgans** [comment]
I wrote a PR for SPM support #6

**Comment by AsafRollout** [comment]
was done
