### ISSUE TITLE
Mac M1 Build Error

### ISSUE THREAD

**Issue by jeremielumandong** [rollout/rox-ios#5]
Building using the latest pod version 4.10.11 with error below.

building for iOS Simulator, but linking in dylib built for iOS, file '..../Pods/ROXCore/RoxSdk/ROXCore.framework/ROXCore' for architecture arm64

**Comment by enricenrich** [comment]
@ adjunct Any update on this?

**Comment by enricenrich** [comment]
@adjunct Any update on this?

**Comment by corporate-fun** [comment]
Any updates on this? I'm also experiencing this

**Comment by elcloudbees** [comment]
Hi @jeremielumandong , @enricenrich , and @corporate-fun , we are looking into this now. I'll write back with an update soon.

**Comment by arnauddorgans** [comment]
any updates ?

**Comment by bkunat** [comment]
ROX is the only dependency in our project with this issue. Any updates on this @elcloudbees?

**Comment by andy-a-o** [comment]
Hi @bkunat @arnauddorgans @corporate-fun @enricenrich @jeremielumandong we're about to release the CocoaPod update solving this issue, but for now you have an option of using Swift Package Manager for installing the ROX SDK. Manually installing XCFramework should work, too.

Cheers

**Comment by andy-a-o** [comment]
https://docs.cloudbees.com/docs/cloudbees-feature-management/latest/getting-started/ios-sdk#_swift_package_manager

**Comment by andy-a-o** [comment]
Hi, small update on this issue.

While the release cycle isn't finished yet, and the docs are still updating, I can suggest trying this solution for Carthage users:

1. Add the following in `Cartfile`:

```
github "rollout/rox-spm"
```

2. Run `carthage update --use-xcframeworks`
3. Add the downloaded binaries to your project. The binaries can be found in `Carthage/Bin` directory.

For Objective-C add `ROXCore.xcframework`.
For Swift add both `ROXCore.xcframework` and `ROX.xcframework`.

For those who are using CocoaPods, we're still preparing the new podspec file which should solve the issue.

**Comment by andy-a-o** [comment]
M1 support added starting from 5.0.13.

### Cocoapods users

Run `pod update ROX`.

### Carthage users

See the above comment https://github.com/rollout/rox-ios/issues/5#issuecomment-1016125972

### Manual installation

Will no longer work except XCFramework manual download. Recommend switching to Swift Package Manager, or any other option above.

**Comment by AsafRollout** [comment]
Thank you @andy-a-o

**Comment by johntmcintosh** [comment]
@andy-a-o , M1 support isn't working for us with the 5.0.13 update, but it looks like the issue may just be limited to the podspec. If you look [here in the ROX.podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/6/9/c/ROX/5.0.13/ROX.podspec.json#L29-L36) and [here in the ROXCore.podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/1/6/b/ROXCore/5.0.13/ROXCore.podspec.json#L24-L31), there is this declaration to exclude arm64 simulator support:

```
  "ios": {
    "pod_target_xcconfig": {
      "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "arm64"
    },
    "user_target_xcconfig": {
      "EXCLUDED_ARCHS[sdk=iphonesimulator*]": "arm64"
    }
  },
```

In the xcframework that's installed it looks like the arm64 simulator slice is actually present. So I think there's a chance that just removing these exclusion lines from the Podspecs would be sufficient to get this working through CocoaPods.
